name: Tests-Lint

on:
  pull_request:
  push:
    # trying and staging branches are for BORS config
    branches:
      - trying
      - staging
      - master

jobs:
  test:
    name: vuepress-plugin-tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: yarn install
    - name: Run tests
      run: yarn run test
    - name: Run linter
      run: yarn run lint
